/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedRaiseTicketRouteImport } from './routes/_protected/raise-ticket'
import { Route as PublicODataODataRouteImport } from './routes/_public/o-data/o-data'
import { Route as PublicAuthRegisterRouteImport } from './routes/_public/auth/register'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as PublicAuthForgotPasswordRouteImport } from './routes/_public/auth/forgot-password'
import { Route as ProtectedTicketpageTicketIdRouteImport } from './routes/_protected/ticketpage/$ticketId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRaiseTicketRoute = ProtectedRaiseTicketRouteImport.update({
  id: '/raise-ticket',
  path: '/raise-ticket',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicODataODataRoute = PublicODataODataRouteImport.update({
  id: '/_public/o-data/o-data',
  path: '/o-data/o-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRegisterRoute = PublicAuthRegisterRouteImport.update({
  id: '/_public/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/_public/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthForgotPasswordRoute =
  PublicAuthForgotPasswordRouteImport.update({
    id: '/_public/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTicketpageTicketIdRoute =
  ProtectedTicketpageTicketIdRouteImport.update({
    id: '/ticketpage/$ticketId',
    path: '/ticketpage/$ticketId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/raise-ticket': typeof ProtectedRaiseTicketRoute
  '/': typeof ProtectedIndexRoute
  '/ticketpage/$ticketId': typeof ProtectedTicketpageTicketIdRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/o-data/o-data': typeof PublicODataODataRoute
}
export interface FileRoutesByTo {
  '/raise-ticket': typeof ProtectedRaiseTicketRoute
  '/': typeof ProtectedIndexRoute
  '/ticketpage/$ticketId': typeof ProtectedTicketpageTicketIdRoute
  '/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/register': typeof PublicAuthRegisterRoute
  '/o-data/o-data': typeof PublicODataODataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/raise-ticket': typeof ProtectedRaiseTicketRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/ticketpage/$ticketId': typeof ProtectedTicketpageTicketIdRoute
  '/_public/auth/forgot-password': typeof PublicAuthForgotPasswordRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/register': typeof PublicAuthRegisterRoute
  '/_public/o-data/o-data': typeof PublicODataODataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/raise-ticket'
    | '/'
    | '/ticketpage/$ticketId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/o-data/o-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/raise-ticket'
    | '/'
    | '/ticketpage/$ticketId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/o-data/o-data'
  id:
    | '__root__'
    | '/_protected'
    | '/_protected/raise-ticket'
    | '/_protected/'
    | '/_protected/ticketpage/$ticketId'
    | '/_public/auth/forgot-password'
    | '/_public/auth/login'
    | '/_public/auth/register'
    | '/_public/o-data/o-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicAuthForgotPasswordRoute: typeof PublicAuthForgotPasswordRoute
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegisterRoute: typeof PublicAuthRegisterRoute
  PublicODataODataRoute: typeof PublicODataODataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/raise-ticket': {
      id: '/_protected/raise-ticket'
      path: '/raise-ticket'
      fullPath: '/raise-ticket'
      preLoaderRoute: typeof ProtectedRaiseTicketRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/o-data/o-data': {
      id: '/_public/o-data/o-data'
      path: '/o-data/o-data'
      fullPath: '/o-data/o-data'
      preLoaderRoute: typeof PublicODataODataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/register': {
      id: '/_public/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof PublicAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/forgot-password': {
      id: '/_public/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof PublicAuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/ticketpage/$ticketId': {
      id: '/_protected/ticketpage/$ticketId'
      path: '/ticketpage/$ticketId'
      fullPath: '/ticketpage/$ticketId'
      preLoaderRoute: typeof ProtectedTicketpageTicketIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedRaiseTicketRoute: typeof ProtectedRaiseTicketRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTicketpageTicketIdRoute: typeof ProtectedTicketpageTicketIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedRaiseTicketRoute: ProtectedRaiseTicketRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTicketpageTicketIdRoute: ProtectedTicketpageTicketIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicAuthForgotPasswordRoute: PublicAuthForgotPasswordRoute,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegisterRoute: PublicAuthRegisterRoute,
  PublicODataODataRoute: PublicODataODataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
